SELECT G.USER_ID, G.NICKNAME, SUM(B.PRICE) TOTAL_SALES
FROM USED_GOODS_BOARD B JOIN USED_GOODS_USER G ON B.WRITER_ID = G.USER_ID
WHERE B.STATUS = 'DONE'
GROUP BY G.USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES